# Generated by Django 5.1 on 2026-01-01 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_hotspot_alter_report_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="authority_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("resolved", "Resolved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
